version: "3.8"
services:
  web:
    build: .
    ports:
      - "0.0.0.0:80:80"
    image: lct2020-api
    volumes:
    - ./models:/lct_rec/models
    environment:
      S3_ACCESS_KEY: $S3_ACCESS_KEY
      S3_SECRET_KEY: $S3_SECRET_KEY
      S3_BUCKET: $S3_BUCKET
